-- Humble Home – products table + image bucket.
-- Run once in Supabase: Dashboard → SQL Editor → New query → paste this file → Run.

-- ---------------------------------------------------------------- products
create table if not exists public.products (
  id bigint generated by default as identity (start with 100000) primary key,
  slug text not null unique,
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists products_touch on public.products;
create trigger products_touch before update on public.products
  for each row execute function public.touch_updated_at();

alter table public.products enable row level security;

-- Everyone can read products (the website); only signed-in users (the dashboard admin) can change them.
drop policy if exists "products are public" on public.products;
create policy "products are public" on public.products
  for select using (true);

drop policy if exists "admins insert products" on public.products;
create policy "admins insert products" on public.products
  for insert to authenticated with check (true);

drop policy if exists "admins update products" on public.products;
create policy "admins update products" on public.products
  for update to authenticated using (true) with check (true);

drop policy if exists "admins delete products" on public.products;
create policy "admins delete products" on public.products
  for delete to authenticated using (true);

-- ---------------------------------------------------------------- product photos
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "product images are public" on storage.objects;
create policy "product images are public" on storage.objects
  for select using (bucket_id = 'product-images');

drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects
  for insert to authenticated with check (bucket_id = 'product-images');

drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects
  for delete to authenticated using (bucket_id = 'product-images');
